
import { Airdrop } from './types';

// Third batch of new airdrops from the Google Spreadsheet
export const newAirdrops3: Airdrop[] = [
  {
    id: '57',
    name: 'Privasea',
    description: 'Privacy-preserving computation protocol for sensitive data processing.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'PRIV',
    estimatedValue: '$15-80',
    startDate: '2024-04-01',
    endDate: '2024-06-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresDiscord: true,
    link: 'https://privasea.tech',
    fundingAmount: '$15M',
    investmentStatus: 'Invest',
    timeline: 'Q2',
    steps: [
      'Complete KYC verification',
      'Test private computation features',
      'Process data through secure nodes',
      'Provide feedback on privacy guarantees'
    ]
  },
  {
    id: '58',
    name: 'Otoroshi Network',
    description: 'API gateway for decentralized services with advanced security features.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'OTO',
    estimatedValue: '$10-50',
    startDate: '2024-03-15',
    endDate: '2024-06-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://otoroshi.network',
    fundingAmount: '$12M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Deploy Otoroshi gateway',
      'Configure API endpoints',
      'Test security features',
      'Provide feedback on performance'
    ]
  },
  {
    id: '59',
    name: 'Walrus',
    description: 'Infrastructure for secure secret management in blockchain applications.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'WLRS',
    estimatedValue: '$15-70',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    status: 'Ended',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://walrus.security',
    fundingAmount: 'Undisclosed',
    investmentStatus: 'Free',
    timeline: 'Over',
    steps: [
      'Test secret management tools',
      'Integrate with wallets and dApps',
      'Report security vulnerabilities',
      'Provide feedback on user experience'
    ]
  },
  {
    id: '60',
    name: 'Pin AI',
    description: 'AI-powered content curation and discovery platform with token incentives.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Solana',
    tokenSymbol: 'PIN',
    estimatedValue: '$10-40',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://pinai.app',
    fundingAmount: '$10M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Create a Pin AI account',
      'Curate and share content',
      'Test AI recommendations',
      'Provide feedback on discovery algorithms'
    ]
  },
  {
    id: '61',
    name: 'Arcium',
    description: 'Smart contract auditing and security protocol with automated vulnerability detection.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ARC',
    estimatedValue: '$15-60',
    startDate: '2024-03-20',
    endDate: '2024-06-20',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://arcium.security',
    fundingAmount: '$9M',
    investmentStatus: 'Invest',
    timeline: 'Q2-Q3',
    steps: [
      'Submit smart contracts for audit',
      'Test vulnerability detection',
      'Participate in bug bounties',
      'Provide feedback on audit reports'
    ]
  },
  {
    id: '62',
    name: 'Nexus',
    description: 'Interoperability protocol connecting different blockchain ecosystems.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'NXS',
    estimatedValue: '$20-100',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://nexus.protocol',
    fundingAmount: '$25M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Test cross-chain messaging',
      'Bridge assets between networks',
      'Interact with connected dApps',
      'Provide feedback on interoperability'
    ]
  },
  {
    id: '63',
    name: 'Unichar L2',
    description: 'Layer 2 scaling solution with unique unicode-based addressing system.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'UNI2',
    estimatedValue: '$30-150',
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://unichar.io',
    fundingAmount: '$178M',
    investmentStatus: 'Invest',
    timeline: 'Q3-Q4',
    steps: [
      'Join Unichar L2 testnet',
      'Create unicode addresses',
      'Test L2 transactions',
      'Provide feedback on UX and performance'
    ]
  },
  {
    id: '64',
    name: 'Anoma',
    description: 'Sovereign, privacy-preserving protocol for decentralized counterparty discovery.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'NOM',
    estimatedValue: '$25-120',
    startDate: '2024-03-15',
    endDate: '2024-06-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://anoma.network',
    fundingAmount: '$57M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Join Anoma testnet',
      'Test private transactions',
      'Participate in counterparty discovery',
      'Provide feedback on privacy features'
    ]
  },
  {
    id: '65',
    name: 'Oshi',
    description: 'Social finance platform combining payments with social interactions.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Solana',
    tokenSymbol: 'OSHI',
    estimatedValue: '$15-80',
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://oshi.fi',
    fundingAmount: '$12.5M',
    investmentStatus: 'Free',
    timeline: 'Q3-Q4',
    steps: [
      'Create an Oshi account',
      'Connect social accounts',
      'Make social payments',
      'Invite friends to the platform'
    ]
  },
  {
    id: '66',
    name: 'NodeGo',
    description: 'Node infrastructure protocol for decentralized application hosting.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'NDG',
    estimatedValue: '$10-50',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://nodego.io',
    fundingAmount: '$8M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Run a NodeGo node',
      'Host applications on the network',
      'Test decentralized hosting features',
      'Provide feedback on node performance'
    ]
  }
];
