
import { Airdrop, InvestmentStatus } from './types';

// New airdrops from the Google Spreadsheet
export const newAirdrops: Airdrop[] = [
  {
    id: '31',
    name: 'Sahara AI',
    description: 'AI platform focused on innovative solutions for decentralized applications.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SAHARA',
    estimatedValue: '$20-100',
    startDate: '2024-03-01',
    endDate: '2024-06-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://sahara.ai',
    fundingAmount: '$49M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Join Sahara AI community',
      'Complete social engagement tasks',
      'Participate in testnet',
      'Hold tokens until snapshot'
    ]
  },
  {
    id: '32',
    name: '0g Labs',
    description: 'Zero-gravity computing platform for blockchain applications with innovative consensus mechanisms.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: '0G',
    estimatedValue: '$50-200',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://0glabs.com',
    fundingAmount: '$325M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Participate in 0g Labs testnet',
      'Complete protocol testing tasks',
      'Provide feedback on their platform',
      'Join community events'
    ]
  },
  {
    id: '33',
    name: 'Layer Edge',
    description: 'Next-generation Layer 2 scaling solution with advanced zero-knowledge technology.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'EDGE',
    estimatedValue: '$30-150',
    startDate: '2024-01-10',
    endDate: '2024-06-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://layeredge.io',
    fundingAmount: 'Undisclosed',
    investmentStatus: 'Free',
    timeline: 'Q1-Q2',
    steps: [
      'Bridge assets to Layer Edge testnet',
      'Complete transactions on the network',
      'Test various dApps in their ecosystem',
      'Participate in community events'
    ]
  },
  {
    id: '34',
    name: 'Humanity Protocol',
    description: 'Identity verification protocol using biometric data and zero-knowledge proofs.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'HMTY',
    estimatedValue: '$20-100',
    startDate: '2024-03-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresTwitter: true,
    link: 'https://humanity.protocol',
    fundingAmount: '$30M',
    investmentStatus: 'Free',
    timeline: 'Q2',
    steps: [
      'Complete identity verification process',
      'Participate in the protocol testing',
      'Provide feedback on user experience',
      'Join community events'
    ]
  },
  {
    id: '35',
    name: 'Onefootball',
    description: 'Sports and football-focused blockchain platform with NFT and fan engagement features.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Polygon',
    tokenSymbol: 'OFB',
    estimatedValue: '$10-50',
    startDate: '2024-04-01',
    endDate: '2024-06-30',
    status: 'Active',
    type: 'NFT',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://onefootball.com',
    fundingAmount: '$307M',
    investmentStatus: 'Free',
    timeline: 'Q2',
    steps: [
      'Create an account on Onefootball platform',
      'Participate in NFT drops',
      'Engage with content and predictions',
      'Refer friends to the platform'
    ]
  },
  {
    id: '36',
    name: 'Gamerboom',
    description: 'Gaming platform that integrates blockchain technology for in-game assets and rewards.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Binance Smart Chain',
    tokenSymbol: 'GBOOM',
    estimatedValue: '$15-80',
    startDate: '2024-03-10',
    endDate: '2024-06-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://gamerboom.io',
    fundingAmount: '$9M',
    investmentStatus: 'Invest',
    timeline: 'Q2-Q3',
    steps: [
      'Create a Gamerboom account',
      'Play supported games',
      'Complete gaming achievements',
      'Participate in tournaments'
    ]
  },
  {
    id: '37',
    name: 'Magic Newton',
    description: 'AI-powered DeFi protocol with predictive trading algorithms.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'MGNW',
    estimatedValue: '$20-100',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://magicnewton.io',
    fundingAmount: '$83M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Join Magic Newton community',
      'Participate in testing phases',
      'Provide feedback on trading algorithms',
      'Complete trading challenges'
    ]
  },
  {
    id: '38',
    name: 'Kite AI',
    description: 'AI companion for traders and investors with market insights and portfolio management.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Solana',
    tokenSymbol: 'KITE',
    estimatedValue: '$30-120',
    startDate: '2024-05-01',
    endDate: '2024-08-01',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: true,
    requiresTwitter: true,
    link: 'https://kiteai.xyz',
    fundingAmount: 'Undisclosed',
    investmentStatus: 'Free',
    timeline: 'Q3',
    steps: [
      'Sign up for Kite AI beta access',
      'Complete profile and preference setup',
      'Test the AI trading assistant',
      'Provide detailed feedback'
    ]
  },
  {
    id: '39',
    name: 'Sentient',
    description: 'Advanced AI infrastructure for decentralized applications with focus on neural networks.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SENT',
    estimatedValue: '$25-120',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://sentient.io',
    fundingAmount: '$85M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Register for Sentient platform',
      'Test AI capabilities',
      'Build or interact with dApps using their tools',
      'Provide development feedback'
    ]
  },
  {
    id: '40',
    name: 'Fraction AI',
    description: 'Fractional AI computing resources for blockchain networks, enabling cost-effective AI capabilities.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Polygon',
    tokenSymbol: 'FRAC',
    estimatedValue: '$10-50',
    startDate: '2024-03-20',
    endDate: '2024-06-20',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://fractionai.io',
    fundingAmount: '$6M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Join Fraction AI platform',
      'Contribute computing resources',
      'Test fractional AI capabilities',
      'Participate in governance proposals'
    ]
  },
  {
    id: '41',
    name: 'Farcaster',
    description: 'Decentralized social media protocol built for the next generation of internet users.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'CAST',
    estimatedValue: '$20-100',
    startDate: '2024-04-10',
    endDate: '2024-07-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://www.farcaster.xyz',
    fundingAmount: '$180M',
    investmentStatus: 'Invest',
    timeline: 'Q2-Q3',
    steps: [
      'Create a Farcaster account',
      'Post regularly on the platform',
      'Engage with other users',
      'Build a following on the network'
    ]
  },
  {
    id: '42',
    name: 'Klok',
    description: 'Time-based blockchain with innovative consensus mechanism for time-sensitive applications.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'KLOK',
    estimatedValue: '$15-70',
    startDate: '2024-05-01',
    endDate: '2024-08-01',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://klok.network',
    fundingAmount: '$9M',
    investmentStatus: 'Free',
    timeline: 'Q3',
    steps: [
      'Join Klok testnet',
      'Test time-based applications',
      'Provide feedback on synchronization',
      'Participate in time-locking challenges'
    ]
  },
  {
    id: '43',
    name: 'Eclipse',
    description: 'Privacy-focused layer-1 blockchain with integrated zero-knowledge proofs.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'ECLP',
    estimatedValue: '$25-120',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://eclipse.network',
    fundingAmount: '$60M',
    investmentStatus: 'Invest',
    timeline: 'Q2-Q3',
    steps: [
      'Create an Eclipse wallet',
      'Participate in privacy protocol testing',
      'Send private transactions',
      'Provide feedback on user experience'
    ]
  }
];
