
import { Airdrop } from './types';

// Second batch of new airdrops from the Google Spreadsheet
export const newAirdrops2: Airdrop[] = [
  {
    id: '44',
    name: 'Sapien',
    description: 'Decentralized social network focusing on human-centric interactions and rewards.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SPN',
    estimatedValue: '$10-50',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://www.sapien.network',
    fundingAmount: '$15.5M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Create a Sapien Network account',
      'Participate in community discussions',
      'Create and share content',
      'Engage with other users'
    ]
  },
  {
    id: '45',
    name: 'Assisterr',
    description: 'AI assistant protocol for blockchain interactions and DeFi management.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ASST',
    estimatedValue: '$5-30',
    startDate: '2024-03-15',
    endDate: '2024-06-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://assisterr.ai',
    fundingAmount: '$1.7M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Install Assisterr browser extension',
      'Connect your wallet',
      'Test AI assistant features',
      'Provide feedback on user experience'
    ]
  },
  {
    id: '46',
    name: 'Hemi Protocol',
    description: 'Cross-chain liquidity protocol with innovative yield generation strategies.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'HEMI',
    estimatedValue: '$15-80',
    startDate: '2024-01-10',
    endDate: '2024-03-31',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://hemi.finance',
    fundingAmount: '$15M',
    investmentStatus: 'Free',
    timeline: 'Q1',
    steps: [
      'Connect your wallet to Hemi Protocol',
      'Provide liquidity to eligible pools',
      'Test cross-chain transfers',
      'Hold position for minimum period'
    ]
  },
  {
    id: '47',
    name: 'Nuffle Labs',
    description: 'Decentralized random number generation protocol for fair and transparent lotteries and games.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'NUFF',
    estimatedValue: '$10-60',
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://nuffle.xyz',
    fundingAmount: '$13M',
    investmentStatus: 'Free',
    timeline: 'Q3',
    steps: [
      'Join Nuffle Labs testnet',
      'Test random number generation',
      'Participate in test games and lotteries',
      'Provide feedback on fairness and transparency'
    ]
  },
  {
    id: '48',
    name: 'Stork',
    description: 'Data delivery protocol for secure and efficient cross-chain messaging.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'STRK',
    estimatedValue: '$5-40',
    startDate: '2024-03-20',
    endDate: '2024-06-20',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://stork.network',
    fundingAmount: '$4M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Test Stork messaging capabilities',
      'Send cross-chain messages',
      'Integrate with other protocols',
      'Report bugs and provide feedback'
    ]
  },
  {
    id: '49',
    name: 'Maida',
    description: 'Decentralized healthcare data management system with privacy-preserving features.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Polygon',
    tokenSymbol: 'MAID',
    estimatedValue: '$20-100',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresTwitter: true,
    link: 'https://maida.health',
    fundingAmount: '$52M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Create a Maida account',
      'Complete health profile setup',
      'Test data sharing features',
      'Provide feedback on privacy controls'
    ]
  },
  {
    id: '50',
    name: 'Zkverify',
    description: 'Zero-knowledge proof identity verification system for decentralized applications.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ZKV',
    estimatedValue: '$15-70',
    startDate: '2024-03-10',
    endDate: '2024-06-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://zkverify.io',
    fundingAmount: '$11M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Test ZK verification process',
      'Create and manage verifiable credentials',
      'Integrate with supported dApps',
      'Provide feedback on user experience'
    ]
  },
  {
    id: '51',
    name: 'Frogmetric',
    description: 'Analytics protocol for on-chain data with AI-powered insights.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'FROG',
    estimatedValue: '$10-50',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://frogmetric.io',
    fundingAmount: '$7M',
    investmentStatus: 'Invest',
    timeline: 'Q2-Q3',
    steps: [
      'Create a Frogmetric account',
      'Test analytics dashboards',
      'Generate reports on crypto assets',
      'Provide feedback on accuracy and usability'
    ]
  },
  {
    id: '52',
    name: 'Exponent x Ratex',
    description: 'Decentralized derivatives trading platform with advanced risk management tools.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'EXPX',
    estimatedValue: '$20-100',
    startDate: '2024-05-01',
    endDate: '2024-08-01',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: true,
    requiresDiscord: true,
    link: 'https://exponent.trade',
    fundingAmount: '$2.1x Undisclosed',
    investmentStatus: 'Invest',
    timeline: 'Q2-Q3',
    steps: [
      'Register for Exponent trading platform',
      'Complete KYC verification',
      'Test derivative trading features',
      'Provide feedback on trading experience'
    ]
  },
  {
    id: '53',
    name: 'Linera',
    description: 'Scalable blockchain with parallel transaction processing for high-throughput applications.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'LIN',
    estimatedValue: '$15-70',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://linera.io',
    fundingAmount: '$12M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Join Linera testnet',
      'Deploy or interact with dApps',
      'Test transaction throughput',
      'Provide feedback on performance'
    ]
  },
  {
    id: '54',
    name: 'Billions',
    description: 'Financial services protocol bridging traditional finance with DeFi.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'BILL',
    estimatedValue: '$20-120',
    startDate: '2024-04-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresTwitter: true,
    link: 'https://billions.finance',
    fundingAmount: 'Undisclosed',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Complete KYC verification',
      'Test financial products',
      'Connect traditional bank accounts',
      'Provide feedback on integration experience'
    ]
  },
  {
    id: '55',
    name: 'Space & Time',
    description: 'Decentralized data warehouse with verifiable computing capabilities.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SxT',
    estimatedValue: '$25-120',
    startDate: '2024-04-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://www.spaceandtime.io',
    fundingAmount: '$50M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Join Space & Time platform',
      'Test data queries and storage',
      'Integrate with supported blockchains',
      'Provide feedback on query performance'
    ]
  },
  {
    id: '56',
    name: 'Fastlane',
    description: 'Transaction routing and execution protocol for optimal DeFi interactions.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'FAST',
    estimatedValue: '$10-60',
    startDate: '2024-03-20',
    endDate: '2024-06-20',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://fastlane.finance',
    fundingAmount: '$8.30M',
    investmentStatus: 'Free',
    timeline: 'Q2-Q3',
    steps: [
      'Install Fastlane SDK',
      'Test transaction routing',
      'Compare gas optimization',
      'Provide feedback on execution efficiency'
    ]
  }
];
