import { Airdrop } from './types';

export const blockchains = [
  'Ethereum',
  'Solana', 
  'Binance Smart Chain',
  'Polygon',
  'Avalanche',
  'Arbitrum',
  'Optimism',
  'Near',
  'Other'
];

export const mockAirdrops: Airdrop[] = [
  {
    id: '1',
    name: 'LayerZero',
    description: 'Omnichain interoperability protocol enabling seamless cross-chain applications. Connect all blockchains with a single transaction.',
    logo: 'https://cryptologos.cc/logos/layerzero-zro-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ZRO',
    estimatedValue: '$2,000 - $5,000',
    startDate: '2024-01-15T00:00:00Z',
    endDate: '2024-08-30T23:59:59Z',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://layerzero.network',
    fundingAmount: '$293M',
    fundingRound: 'Series B',
    riskLevel: 'low',
    communityRating: 4.8,
    totalReviews: 1247,
    successRate: 85,
    totalParticipants: 125000,
    steps: [
      'Bridge tokens between different chains using LayerZero',
      'Use Stargate Finance for cross-chain swaps',
      'Interact with omnichain NFTs',
      'Provide liquidity on supported DEXs'
    ],
    reviews: [
      {
        id: '1',
        userId: 'user1',
        username: 'CryptoExplorer',
        rating: 5,
        comment: 'Amazing protocol! The cross-chain functionality is seamless and the team is very active.',
        date: '2024-07-01T00:00:00Z',
        helpful: 23,
        verified: true
      }
    ]
  },
  {
    id: '2',
    name: 'zkSync Era',
    description: 'Ethereum Layer 2 scaling solution using zero-knowledge proofs. Experience faster and cheaper transactions.',
    logo: 'https://cryptologos.cc/logos/zksync-zk-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ZK',
    estimatedValue: '$1,500 - $3,000',
    startDate: '2024-02-01T00:00:00Z',
    endDate: '2024-09-15T23:59:59Z',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresTwitter: false,
    link: 'https://zksync.io',
    fundingAmount: '$458M',
    fundingRound: 'Series C',
    riskLevel: 'low',
    communityRating: 4.6,
    totalReviews: 892,
    successRate: 78,
    totalParticipants: 89000,
    steps: [
      'Bridge ETH to zkSync Era',
      'Make transactions on Era network',
      'Use dApps built on zkSync',
      'Provide liquidity to Era-based protocols'
    ]
  },
  {
    id: '3',
    name: 'Arbitrum',
    description: 'Leading Ethereum Layer 2 solution with optimistic rollup technology. Lower fees, faster transactions.',
    logo: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    blockchain: 'Arbitrum',
    tokenSymbol: 'ARB',
    estimatedValue: '$800 - $2,000',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-07-31T23:59:59Z',
    status: 'Ended',
    type: 'Governance',
    requiresKYC: false,
    link: 'https://arbitrum.io',
    fundingAmount: '$120M',
    fundingRound: 'Series A',
    riskLevel: 'low',
    communityRating: 4.7,
    totalReviews: 1534,
    successRate: 92,
    totalParticipants: 156000,
    steps: [
      'Bridge assets to Arbitrum One',
      'Trade on Arbitrum DEXs',
      'Use Arbitrum-based DeFi protocols',
      'Participate in governance voting'
    ]
  },
  {
    id: '4',
    name: 'Scroll',
    description: 'zkEVM-based Layer 2 for Ethereum. Native compatibility with existing Ethereum applications.',
    logo: 'https://cryptologos.cc/logos/scroll-scr-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SCR',
    estimatedValue: '$500 - $1,200',
    startDate: '2024-03-01T00:00:00Z',
    endDate: '2024-10-30T23:59:59Z',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://scroll.io',
    fundingAmount: '$83M',
    fundingRound: 'Series A',
    riskLevel: 'medium',
    communityRating: 4.3,
    totalReviews: 456,
    successRate: 68,
    totalParticipants: 34000,
    steps: [
      'Bridge tokens to Scroll Alpha testnet',
      'Deploy contracts on Scroll',
      'Use Scroll-based applications',
      'Participate in community events'
    ]
  },
  {
    id: '5',
    name: 'Starknet',
    description: 'Decentralized Layer 2 network using STARK proofs. Unlimited scale for Ethereum applications.',
    logo: 'https://cryptologos.cc/logos/starknet-strk-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'STRK',
    estimatedValue: '$1,000 - $2,500',
    startDate: '2024-02-15T00:00:00Z',
    endDate: '2024-08-15T23:59:59Z',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresDiscord: true,
    link: 'https://starknet.io',
    fundingAmount: '$182M',
    fundingRound: 'Series D',
    riskLevel: 'medium',
    communityRating: 4.4,
    totalReviews: 723,
    successRate: 74,
    totalParticipants: 67000,
    steps: [
      'Deploy smart contracts on Starknet',
      'Bridge assets using StarkGate',
      'Use Cairo programming language',
      'Participate in Starknet governance'
    ]
  },
  {
    id: '6',
    name: 'Polygon zkEVM',
    description: 'Ethereum-equivalent zkEVM scaling solution. Full Ethereum compatibility with zero-knowledge security.',
    logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
    blockchain: 'Polygon',
    tokenSymbol: 'POL',
    estimatedValue: '$300 - $800',
    startDate: '2024-01-10T00:00:00Z',
    endDate: '2024-09-30T23:59:59Z',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://polygon.technology/polygon-zkevm',
    fundingAmount: '$450M',
    fundingRound: 'Series B',
    riskLevel: 'low',
    communityRating: 4.5,
    totalReviews: 934,
    successRate: 81,
    totalParticipants: 78000,
    steps: [
      'Bridge tokens to Polygon zkEVM',
      'Use zkEVM-based dApps',
      'Provide liquidity on zkEVM DEXs',
      'Participate in validator staking'
    ]
  }
];
