
import { Airdrop, BlockchainType } from './types';

export const blockchains: BlockchainType[] = [
  'Ethereum',
  'Solana',
  'Binance Smart Chain',
  'Polygon',
  'Avalanche',
  'Arbitrum',
  'Optimism',
  'Near',
  'Other',
];

export const mockAirdrops: Airdrop[] = [
  {
    id: '1',
    name: 'Arbitrum Odyssey',
    description: 'Participate in the Arbitrum Odyssey event to earn ARB tokens as a reward for early adoption.',
    logo: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    blockchain: 'Arbitrum',
    tokenSymbol: 'ARB',
    estimatedValue: '$50-200',
    startDate: '2023-12-01',
    endDate: '2024-01-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://arbitrum.io',
    steps: [
      'Connect your wallet to Arbitrum',
      'Complete at least 5 transactions on the network',
      'Interact with at least 3 different protocols',
      'Hold a minimum balance until the snapshot date'
    ]
  },
  {
    id: '2',
    name: 'Solana Saga Drop',
    description: 'Early users of the Solana Saga phone will receive a special token airdrop.',
    logo: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    blockchain: 'Solana',
    tokenSymbol: 'SOL',
    estimatedValue: '$100-500',
    startDate: '2023-11-15',
    endDate: '2024-02-28',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    link: 'https://solana.com',
    steps: [
      'Purchase a Solana Saga phone',
      'Activate and set up the device',
      'Register your wallet on the Solana Saga platform',
      'Complete KYC verification'
    ]
  },
  {
    id: '3',
    name: 'Uniswap V4',
    description: 'Potential airdrop for early users of Uniswap V4 when it launches.',
    logo: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'UNI',
    estimatedValue: '$200-1000',
    startDate: '2024-03-01',
    endDate: '2024-06-30',
    status: 'Upcoming',
    type: 'Governance',
    requiresKYC: false,
    link: 'https://uniswap.org',
    steps: [
      'Use Uniswap V4 when it launches',
      'Provide liquidity to eligible pools',
      'Hold your position for the required period',
      'Vote on at least one governance proposal'
    ]
  },
  {
    id: '4',
    name: 'Optimism Grants',
    description: 'Contribute to Optimism ecosystem projects to qualify for OP tokens distribution.',
    logo: 'https://cryptologos.cc/logos/optimism-ethereum-op-logo.png',
    blockchain: 'Optimism',
    tokenSymbol: 'OP',
    estimatedValue: '$20-150',
    startDate: '2023-10-10',
    endDate: '2024-01-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://optimism.io',
    steps: [
      'Contribute to an Optimism ecosystem project',
      'Submit your contribution for review',
      'Get verified by the Optimism team',
      'Connect your wallet for distribution'
    ]
  },
  {
    id: '5',
    name: 'Polygon zkEVM Beta',
    description: 'Participate in the zkEVM Beta testing to qualify for MATIC rewards.',
    logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
    blockchain: 'Polygon',
    tokenSymbol: 'MATIC',
    estimatedValue: '$30-120',
    startDate: '2023-11-20',
    endDate: '2024-02-20',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://polygon.technology',
    steps: [
      'Join the Polygon zkEVM Beta program',
      'Bridge assets to zkEVM',
      'Complete test transactions and provide feedback',
      'Report bugs or suggest improvements'
    ]
  },
  {
    id: '6',
    name: 'Avalanche Multiverse',
    description: 'NFT collection for Avalanche subnet creators and early supporters.',
    logo: 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
    blockchain: 'Avalanche',
    tokenSymbol: 'AVAX',
    estimatedValue: '$50-200',
    startDate: '2023-12-15',
    endDate: '2024-03-15',
    status: 'Active',
    type: 'NFT',
    requiresKYC: true,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://avax.network',
    steps: [
      'Create or support an Avalanche subnet',
      'Submit your project for review',
      'Complete KYC verification',
      'Mint your NFT during the eligible period'
    ]
  },
  {
    id: '7',
    name: 'BNB Chain Pioneers',
    description: 'Early adopters program for BNB Chain applications with token rewards.',
    logo: 'https://cryptologos.cc/logos/bnb-bnb-logo.png',
    blockchain: 'Binance Smart Chain',
    tokenSymbol: 'BNB',
    estimatedValue: '$40-160',
    startDate: '2023-09-01',
    endDate: '2024-01-31',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    link: 'https://www.bnbchain.org',
    steps: [
      'Create a BNB Chain wallet',
      'Complete KYC verification',
      'Use at least 5 different BNB Chain applications',
      'Hold eligible tokens until the snapshot date'
    ]
  },
  {
    id: '8',
    name: 'Near Protocol Horizon',
    description: 'Community program for NEAR developers with token incentives.',
    logo: 'https://cryptologos.cc/logos/near-protocol-near-logo.png',
    blockchain: 'Near',
    tokenSymbol: 'NEAR',
    estimatedValue: '$75-300',
    startDate: '2024-01-15',
    endDate: '2024-04-15',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresDiscord: true,
    link: 'https://near.org',
    steps: [
      'Join the NEAR developer community',
      'Contribute to at least one NEAR project',
      'Participate in community calls and events',
      'Register your wallet for the distribution'
    ]
  },
  {
    id: '9',
    name: 'Ethereum Staking Rewards',
    description: 'Special distribution for long-term ETH stakers post-Shapella upgrade.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ETH',
    estimatedValue: '$100-1000',
    startDate: '2024-02-01',
    endDate: '2024-05-01',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    link: 'https://ethereum.org',
    steps: [
      'Stake ETH through a participating service',
      'Maintain your stake for the minimum required period',
      'Register your address on the rewards portal',
      'Claim your rewards after the distribution date'
    ]
  },
  {
    id: '10',
    name: 'Cosmos Hub Governance',
    description: 'Distribution for active governance participants in the Cosmos ecosystem.',
    logo: 'https://cryptologos.cc/logos/cosmos-atom-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'ATOM',
    estimatedValue: '$50-250',
    startDate: '2023-12-10',
    endDate: '2024-03-10',
    status: 'Active',
    type: 'Governance',
    requiresKYC: false,
    link: 'https://cosmos.network',
    steps: [
      'Hold ATOM in a non-custodial wallet',
      'Participate in at least 10 governance proposals',
      'Maintain a minimum balance throughout the period',
      'Register for the distribution after the qualifying period'
    ]
  },
  // New airdrops from Telegram channel
  {
    id: '11',
    name: 'Blast Protocol',
    description: 'A new L2 solution with native yield for ETH and stablecoins, founded by Tieshun Roquerre (Blur founder).',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'BLAST',
    estimatedValue: '$100-500',
    startDate: '2024-05-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://blast.io/en',
    steps: [
      'Connect your ETH wallet to Blast',
      'Bridge assets to the Blast L2',
      'Interact with protocols on the network',
      'Complete social media tasks',
      'Maintain activity until the airdrop snapshot'
    ]
  },
  {
    id: '12',
    name: 'Zeta Markets',
    description: 'Solana-based decentralized derivatives exchange offering futures and options trading.',
    logo: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    blockchain: 'Solana',
    tokenSymbol: 'ZETA',
    estimatedValue: '$50-300',
    startDate: '2024-04-15',
    endDate: '2024-06-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://zeta.markets',
    steps: [
      'Create an account on Zeta Markets',
      'Complete KYC verification if needed',
      'Trade options or futures on the platform',
      'Maintain a minimum trading volume',
      'Join their community channels'
    ]
  },
  {
    id: '13',
    name: 'LayerZero',
    description: 'Omnichain interoperability protocol enabling cross-chain messaging and communication.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ZRO',
    estimatedValue: '$100-400',
    startDate: '2024-03-20',
    endDate: '2024-08-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://layerzero.network',
    steps: [
      'Bridge assets across different chains using LayerZero',
      'Interact with protocols integrated with LayerZero',
      'Complete specific transactions on supported chains',
      'Follow and engage with social media channels'
    ]
  },
  {
    id: '14',
    name: 'Polyhedra Network',
    description: 'ZK rollup infrastructure for cross-chain communication and interoperability.',
    logo: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
    blockchain: 'Polygon',
    tokenSymbol: 'POLY',
    estimatedValue: '$50-250',
    startDate: '2024-04-01',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://polyhedra.network',
    steps: [
      'Use Polyhedra ZK bridges to transfer assets',
      'Interact with dApps in their ecosystem',
      'Complete social engagement tasks',
      'Hold transactions until snapshot date'
    ]
  },
  {
    id: '15',
    name: 'Merlin Chain',
    description: 'A Bitcoin Layer-2 solution focused on bringing AI capabilities to Bitcoin.',
    logo: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'MERL',
    estimatedValue: '$30-200',
    startDate: '2024-03-15',
    endDate: '2024-06-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://merlinchain.io',
    steps: [
      'Bridge BTC to Merlin Chain',
      'Interact with AI-powered dApps',
      'Complete social tasks and community engagement',
      'Hold bridged assets until the snapshot date'
    ]
  },
  {
    id: '16',
    name: 'ZKsync Era',
    description: 'Layer-2 scaling solution for Ethereum using zero-knowledge proofs.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ZKS',
    estimatedValue: '$100-500',
    startDate: '2024-02-10',
    endDate: '2024-08-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://zksync.io',
    steps: [
      'Bridge ETH or tokens to ZKsync Era',
      'Perform transactions on the network',
      'Interact with dApps in the ecosystem',
      'Maintain activity for potential retroactive airdrop'
    ]
  },
  {
    id: '17',
    name: 'Taiko',
    description: 'Decentralized, Ethereum-equivalent ZK-Rollup focused on full EVM compatibility.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'TAIKO',
    estimatedValue: '$50-300',
    startDate: '2024-03-01',
    endDate: '2024-06-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://taiko.xyz',
    steps: [
      'Bridge assets to Taiko testnet',
      'Perform transactions on the network',
      'Test various dApps in their ecosystem',
      'Provide feedback and report bugs',
      'Participate in community events'
    ]
  },
  {
    id: '18',
    name: 'Linea',
    description: 'Ethereum Layer-2 scaling solution developed by ConsenSys using zero-knowledge technology.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'LINEA',
    estimatedValue: '$50-300',
    startDate: '2024-03-15',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://linea.build',
    steps: [
      'Bridge ETH to Linea',
      'Use dApps deployed on Linea',
      'Complete transactions regularly',
      'Maintain activity until potential airdrop announcement'
    ]
  },
  {
    id: '19',
    name: 'Scroll',
    description: 'Layer-2 zkEVM scaling solution for Ethereum focused on preserving compatibility.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SCROLL',
    estimatedValue: '$50-250',
    startDate: '2024-02-20',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://scroll.io',
    steps: [
      'Bridge assets to Scroll',
      'Interact with dApps on the network',
      'Complete regular transactions',
      'Engage with the community',
      'Maintain activity through potential snapshot periods'
    ]
  },
  {
    id: '20',
    name: 'Sei Network',
    description: 'Layer-1, optimized for trading, with parallelized execution and fast finality.',
    logo: 'https://cryptologos.cc/logos/sei-network-sei-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'SEI',
    estimatedValue: '$100-400',
    startDate: '2024-03-10',
    endDate: '2024-06-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: true,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://www.sei.io',
    steps: [
      'Create a Sei wallet',
      'Complete KYC verification',
      'Participate in testnet activities',
      'Trade on Sei-based exchanges',
      'Engage with community campaigns'
    ]
  },
  
  // Adding new projects with funding information
  {
    id: '21',
    name: 'Mantle Network',
    description: 'Layer-2 scaling solution that combines modular design with EVM equivalence using optimistic rollups.',
    logo: 'https://cryptologos.cc/logos/mantle-mnt-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'MNT',
    estimatedValue: '$50-300',
    startDate: '2024-03-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://www.mantle.xyz',
    fundingAmount: '$200M',
    fundingRound: 'Series A',
    steps: [
      'Bridge ETH to Mantle Network',
      'Use dApps on Mantle ecosystem',
      'Interact with their protocol regularly',
      'Participate in community events',
      'Maintain wallet activity for potential retroactive airdrop'
    ]
  },
  {
    id: '22',
    name: 'Starknet',
    description: 'Layer-2 scaling solution for Ethereum using STARK proofs to enable scalable and secure smart contracts.',
    logo: 'https://cryptologos.cc/logos/starknet-strk-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'STRK',
    estimatedValue: '$100-500',
    startDate: '2024-02-20',
    endDate: '2024-06-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://www.starknet.io',
    fundingAmount: '$50M',
    fundingRound: 'Strategic',
    steps: [
      'Bridge assets to Starknet',
      'Interact with Starknet dApps',
      'Complete transactions on the network',
      'Participate in governance if available',
      'Use Starknet regularly for a potential airdrop'
    ]
  },
  {
    id: '23',
    name: 'Celestia',
    description: 'First modular blockchain network to scale by decoupling consensus from execution, enabling anyone to deploy their own blockchain.',
    logo: 'https://cryptologos.cc/logos/celestia-tia-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'TIA',
    estimatedValue: '$50-300',
    startDate: '2024-03-01',
    endDate: '2024-06-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://celestia.org',
    fundingAmount: '$55M',
    fundingRound: 'Series A+B',
    steps: [
      'Create a wallet for Celestia',
      'Participate in testnet activities',
      'Engage with their community',
      'Test Celestia\'s modular architecture',
      'Submit feedback through official channels'
    ]
  },
  {
    id: '24',
    name: 'Fuel Network',
    description: 'Fastest modular execution layer, designed to scale Ethereum with faster transactions and lower fees.',
    logo: 'https://cryptologos.cc/logos/fuel-fuel-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'FUEL',
    estimatedValue: '$50-250',
    startDate: '2024-04-01',
    endDate: '2024-07-30',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://fuel.network',
    fundingAmount: '$80M',
    fundingRound: 'Series B',
    steps: [
      'Connect to Fuel Network beta',
      'Deploy smart contracts using Sway language',
      'Test transaction throughput',
      'Provide feedback on developer tools',
      'Engage with the Fuel community'
    ]
  },
  {
    id: '25',
    name: 'Eigenlayer',
    description: 'Ethereum restaking protocol allowing ETH stakers to secure multiple networks simultaneously without additional capital.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'EIGEN',
    estimatedValue: '$100-400',
    startDate: '2024-03-10',
    endDate: '2024-08-10',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://www.eigenlayer.xyz',
    fundingAmount: '$100M',
    fundingRound: 'Series A',
    steps: [
      'Stake ETH through Eigenlayer protocol',
      'Participate in various AVSs (actively validated services)',
      'Maintain stake for minimum required period',
      'Engage with governance proposals',
      'Stay updated with Eigenlayer developments'
    ]
  },
  {
    id: '26',
    name: 'Neutron',
    description: 'Smart contract platform secured by Cosmos Hub, enabling interoperable dApps with CosmWasm contracts.',
    logo: 'https://cryptologos.cc/logos/cosmos-atom-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'NTRN',
    estimatedValue: '$30-150',
    startDate: '2024-02-15',
    endDate: '2024-05-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://neutron.org',
    fundingAmount: '$25M',
    fundingRound: 'Seed',
    steps: [
      'Create a Neutron wallet',
      'Stake ATOM or NTRN tokens',
      'Test dApp functionality',
      'Participate in on-chain governance',
      'Engage with the Neutron community'
    ]
  },
  {
    id: '27',
    name: 'Berachain',
    description: 'EVM-compatible blockchain with a novel consensus mechanism called Proof of Liquidity.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'BERA',
    estimatedValue: '$100-500',
    startDate: '2024-05-01',
    endDate: '2024-09-01',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://www.berachain.com',
    fundingAmount: '$42M',
    fundingRound: 'Series A',
    steps: [
      'Join Berachain testnet (Artio)',
      'Interact with Bex (their DEX)',
      'Participate in the Honey farming game',
      'Complete regular transactions',
      'Follow social media for airdrop announcements'
    ]
  },
  {
    id: '28',
    name: 'Wormhole',
    description: 'Generic cross-chain messaging protocol that connects multiple blockchains, enabling transfers and communication.',
    logo: 'https://cryptologos.cc/logos/wormhole-w-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'W',
    estimatedValue: '$50-300',
    startDate: '2024-04-15',
    endDate: '2024-08-15',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    link: 'https://wormhole.com',
    fundingAmount: '$400M',
    fundingRound: 'Strategic',
    steps: [
      'Use Wormhole for cross-chain transfers',
      'Bridge assets between supported chains',
      'Interact with protocols that use Wormhole',
      'Maintain activity across multiple chains',
      'Follow official announcements for airdrop details'
    ]
  },
  {
    id: '29',
    name: 'Injective',
    description: 'Layer-1 blockchain built for finance, featuring a fast decentralized exchange and derivatives trading.',
    logo: 'https://cryptologos.cc/logos/injective-inj-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'INJ',
    estimatedValue: '$50-200',
    startDate: '2024-03-01',
    endDate: '2024-07-01',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://injective.com',
    fundingAmount: '$40M',
    fundingRound: 'Series A',
    steps: [
      'Trade on Injective Protocol',
      'Provide liquidity to markets',
      'Participate in governance',
      'Interact with Injective ecosystem dApps',
      'Maintain regular activity on the platform'
    ]
  },
  {
    id: '30',
    name: 'Monad',
    description: 'High-performance Layer-1 blockchain focused on scaling with sequential execution and parallel verification.',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Other',
    tokenSymbol: 'MONAD',
    estimatedValue: '$100-400',
    startDate: '2024-06-01',
    endDate: '2024-09-30',
    status: 'Upcoming',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://monad.xyz',
    fundingAmount: '$300M',
    fundingRound: 'Multiple rounds',
    steps: [
      'Join the Monad testnet when available',
      'Deploy or interact with dApps on Monad',
      'Test transaction throughput',
      'Provide developer feedback',
      'Follow official channels for airdrop announcements'
    ]
  },
  
  // Adding new projects from the spreadsheet
  {
    id: '31',
    name: 'Mantle',
    description: 'Layer-2 scaling solution using optimistic rollups with a modular design',
    logo: 'https://cryptologos.cc/logos/mantle-mnt-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'MNT',
    estimatedValue: '$100-500',
    startDate: '2023-07-14',
    endDate: '2024-07-14',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    link: 'https://www.mantle.xyz',
    fundingAmount: '$200M',
    fundingRound: 'Series A',
    steps: [
      'Bridge ETH to Mantle Network',
      'Use dApps in the Mantle ecosystem',
      'Hold tokens until airdrop snapshot'
    ]
  },
  {
    id: '32',
    name: 'zkSync',
    description: 'ZK rollup Layer-2 scaling protocol for Ethereum',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'ZKS',
    estimatedValue: '$100-500',
    startDate: '2023-12-01',
    endDate: '2024-09-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://zksync.io',
    fundingAmount: '$458M',
    fundingRound: 'Series C',
    steps: [
      'Bridge assets to zkSync Era',
      'Use zkSync dApps',
      'Trade regularly on the network'
    ]
  },
  {
    id: '33',
    name: 'Starknet',
    description: 'ZK rollup Layer-2 scaling protocol using Cairo programming language',
    logo: 'https://cryptologos.cc/logos/starknet-strk-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'STRK',
    estimatedValue: '$100-400',
    startDate: '2023-12-01',
    endDate: '2024-09-30',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://starknet.io',
    fundingAmount: '$100M',
    fundingRound: 'Series A',
    steps: [
      'Bridge assets to Starknet',
      'Use DeFi protocols on Starknet', 
      'Interact with dApps in the ecosystem'
    ]
  },
  {
    id: '34',
    name: 'Linea',
    description: 'Ethereum Layer-2 scaling solution by ConsenSys using ZK technology',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'LINEA',
    estimatedValue: '$50-300',
    startDate: '2023-07-12',
    endDate: '2024-07-12',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://linea.build',
    fundingAmount: 'Unknown',
    fundingRound: 'Backed by ConsenSys',
    steps: [
      'Bridge ETH to Linea',
      'Use dApps on Linea',
      'Engage with Linea ecosystem'
    ]
  },
  {
    id: '35',
    name: 'Scroll',
    description: 'Layer-2 zkEVM scaling solution for Ethereum',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'SCROLL',
    estimatedValue: '$50-300',
    startDate: '2023-10-19',
    endDate: '2024-10-19',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    link: 'https://scroll.io',
    fundingAmount: '$80M',
    fundingRound: 'Series A',
    steps: [
      'Bridge assets to Scroll',
      'Complete transactions on Scroll',
      'Use dApps in the ecosystem'
    ]
  },
  {
    id: '36',
    name: 'Taiko',
    description: 'Decentralized, Ethereum-equivalent ZK-Rollup',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    blockchain: 'Ethereum',
    tokenSymbol: 'TAIKO',
    estimatedValue: '$50-300',
    startDate: '2024-01-15',
    endDate: '2024-07-15',
    status: 'Active',
    type: 'Token',
    requiresKYC: false,
    requiresTwitter: true,
    requiresDiscord: true,
    link: 'https://taiko.xyz',
    fundingAmount: '$15M',
    fundingRound: 'Seed',
    steps: [
      'Bridge assets to Taiko testnet',
      'Perform transactions on the network',
      'Test dApps in their ecosystem',
      'Provide feedback and report bugs'
    ]
  }
];
